services:
  db:
    image: postgres:16.2-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build:
      context: ../test_website
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_value:/var/html/static/:ro
      - media_value:/var/html/media/:ro
    depends_on:
      - web

volumes:
  postgres_data:
  static_value:
  media_value:
