# Generated by Django 4.2 on 2024-05-02 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название категории', max_length=20, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Укажите slug', max_length=20, unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название услуги', max_length=50, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, help_text='Введите описание услуги', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Укажите стоимость', max_digits=8, verbose_name='Цена')),
                ('status', models.CharField(choices=[('TODO', 'Оформлен'), ('IN_PROGRESS', 'В работе'), ('IN_REVIEW', 'На проверке'), ('TO_FIX', 'На доработку'), ('DONE', 'Выполнен'), ('CANCEL', 'Отменен')], help_text='Выберите статус заказа', max_length=11, verbose_name='Статус заказа')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название услуги', max_length=50, verbose_name='Название услуги')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', upload_to='services/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, help_text='Введите описание услуги', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Укажите стоимость', max_digits=8, verbose_name='Цена')),
                ('category', models.ForeignKey(help_text='Выберите категорию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.category', verbose_name='Категория')),
            ],
        ),
    ]
