# Generated by Django 4.2 on 2024-04-29 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='executor',
            field=models.ForeignKey(help_text='Укажите исполнителя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(help_text='Укажите заказчика', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_customer', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='order',
            name='executor',
            field=models.ForeignKey(help_text='Укажите исполнителя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(help_text='Укажите услугу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='services.service', verbose_name='Заказанная услуга'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('name', 'executor')},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('service', 'customer')},
        ),
    ]
