# Generated by Django 4.2 on 2024-04-26 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='esecutor',
            field=models.ForeignKey(help_text='Укажите исполнителя', on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(help_text='Укажите заказчика', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(help_text='Укажите услугу', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='services.service', verbose_name='Заказанная услуга'),
        ),
    ]
