# Generated by Django 4.2 on 2024-04-27 21:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_alter_order_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='esecutor',
            new_name='executor',
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('name', 'executor')},
        ),
    ]
