# Generated by Django 4.2 on 2024-04-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_order_customer_alter_order_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение', upload_to='services/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('TODO', 'Оформлен'), ('IN_PROGRESS', 'В работе'), ('IN_REVIEW', 'На проверке'), ('TO_FIX', 'На доработку'), ('DONE', 'Выполнен'), ('CANCEL', 'Отменен')], help_text='Выберите статус заказа', max_length=11, verbose_name='Статус заказа'),
        ),
    ]
