# Generated by Django 4.2 on 2024-05-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_image_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Укажите slug', max_length=20, unique=True, verbose_name='Slug'),
        ),
    ]
