# Generated by Django 4.2 on 2024-04-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('TODO', 'Оформлен'), ('IN_PROGRESS', 'В работе'), ('IN_REVIEW', 'На проверке'), ('DONE', 'Выполнен')], help_text='Выберите статус заказа', max_length=11, verbose_name='Статус заказа'),
        ),
    ]
